<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="6622" started-at="2019-10-28T16:33:45Z" finished-at="2019-10-28T16:33:51Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="6622" started-at="2019-10-28T16:33:45Z" finished-at="2019-10-28T16:33:51Z">
      <class name="dummyapiexample.restapi.tests.RestAPIExampleTests">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:dummyapiexample.restapi.tests.RestAPIExampleTests@2a18f23c]" name="beforeTest" is-config="true" duration-ms="946" started-at="2019-10-28T22:03:45Z" finished-at="2019-10-28T22:03:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="getSpecificEmployeeIdRecord()[pri:0, instance:dummyapiexample.restapi.tests.RestAPIExampleTests@2a18f23c]" name="getSpecificEmployeeIdRecord" duration-ms="3387" started-at="2019-10-28T22:03:45Z" finished-at="2019-10-28T22:03:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getSpecificEmployeeIdRecord -->
        <test-method status="FAIL" signature="getSpecificEmployeeIdRecordInvalid()[pri:0, instance:dummyapiexample.restapi.tests.RestAPIExampleTests@2a18f23c]" name="getSpecificEmployeeIdRecordInvalid" duration-ms="972" started-at="2019-10-28T22:03:49Z" finished-at="2019-10-28T22:03:50Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [404] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [404] but found [200]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:372)
	at org.testng.Assert.assertEquals(Assert.java:382)
	at dummyapiexample.restapi.tests.RestAPIExampleTests.getSpecificEmployeeIdRecordInvalid(RestAPIExampleTests.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getSpecificEmployeeIdRecordInvalid -->
        <test-method status="PASS" signature="retrieveAllEmployeeRecords()[pri:0, instance:dummyapiexample.restapi.tests.RestAPIExampleTests@2a18f23c]" name="retrieveAllEmployeeRecords" duration-ms="1295" started-at="2019-10-28T22:03:50Z" finished-at="2019-10-28T22:03:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- retrieveAllEmployeeRecords -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:dummyapiexample.restapi.tests.RestAPIExampleTests@2a18f23c]" name="afterTest" is-config="true" duration-ms="0" started-at="2019-10-28T22:03:51Z" finished-at="2019-10-28T22:03:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- dummyapiexample.restapi.tests.RestAPIExampleTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
